import React from 'react';
import './App.css';
import logo from './logo2 1.png';
import img1 from './img1.png';
import img2 from './img2.png';
import img3 from './img3.png';

const App = () => {
  return (
    <div className="App">
      {/* Navigation Bar */}
      <nav>
        <ul>
          <li><a href="#head">HOME</a></li>
          <li><a href="#ouraim">OUR AIM</a></li>
          <li><a href="#about">ABOUT</a></li>
          <li><a href="#downloads">DOWNLOADS</a></li>
          <li><a href="#report">REPORT</a></li>
        </ul>
      </nav>

      {/* Header Section */}
      <section id="head" className="head">
        <div className="logo">
          <img src={logo} alt="Logo" />
          <p>OFFY<span>.AI</span></p>
        </div>
        <div className="title">
          <h1>PRIVACY IN YOUR HANDS</h1>
          <h2>Ai without Wifi</h2>
        </div>
        <p className="tagline">Powered by Google Gemma AI Model</p>
      </section>

      {/* Our Aim Section */}
      <section id="ouraim" className="section">
        <div>
          <h2>Our Aim</h2>
          <p>
            To make AI models accessible to everyone, especially in rural areas, through a mobile application that 
            operates seamlessly without requiring an internet connection. We strive to bridge the digital divide 
            and empower communities with cutting-edge technology, ensuring that connectivity challenges do not 
            hinder progress and opportunity.
          </p>
        </div>
        <img src={img1} alt="Our Aim" />
      </section>

      {/* About Section */}
      <section id="about" className="section">
        <h2>About</h2>
        <div className="question">
          <img src={img2} alt="About" />
          <div>
            <h3>Why Choose Offy.AI?</h3>
            <p>
              Offy.AI is a revolutionary mobile application designed to provide advanced AI capabilities 
              without the need for an internet connection. Whether you're traveling, working in remote 
              locations, or simply prioritizing privacy, Offy.AI ensures you're never disconnected 
              from the intelligence you need.
            </p>
          </div>
        </div>
        <div className="fea_and_cas">
          <div>
            <h3>Features</h3>
            <ul>
              <li>Fully Offline Functionality</li>
              <li>Enhanced Privacy and Security</li>
              <li>High-Speed Processing</li>
              <li>Energy-Efficient AI Models</li>
            </ul>
            <h3>Use Cases</h3>
            <ul>
              <li>Remote Work and Study</li>
              <li>Travel and Adventure</li>
              <li>Data-Sensitive Environments</li>
              <li>Everyday Assistance</li>
            </ul>
          </div>
          <img src={img3} alt="Features and Use Cases" />
        </div>
      </section>

      {/* Downloads Section */}
      <section id="downloads" className="section">
        <h2>Download</h2>
        <div className="tagline">
          <h3>READY TO GO OFFLINE</h3>
          <h4>GET OFFY.AI TODAY!</h4>
        </div>
        <div className="button">
          <a href="https://www.dropbox.com/scl/fi/x12mmzh1s1lta1d4ohbdx/offyai.apk?rlkey=l65qavrsy6fe070opmgqpuyef&st=ax1k8nvq&dl=1" target="_blank" rel="noopener noreferrer">
            <button>Download Here</button>
          </a>
        </div>
      </section>

      {/* Report Section */}
      <section id="report" className="section">
        <h2>Report</h2>
        <p>
          Any issues faced in the application? Kindly report on my <br />
          LinkedIn profile or via email. <br /><br />
          LinkedIn -<a href="https://www.linkedin.com/in/nijeesh-nj-062468285/">https://www.linkedin.com/in/nijeesh-nj-062468285/</a> <br /> Gmail ID - nijeesh10th@gmail.com
        </p>
      </section>

      {/* Footer */}
      <footer>
        <p>© 2025 Offy.AI. All Rights Reserved.</p>
        <p>Developed by: Nijeesh NJ</p>
        <p style={{ color: 'red' }}>All images and content are completely generated by AI.</p>
      </footer>
    </div>
  );
};

export default App;
  